package backend.common;

public enum ExceptionCodeEnum {

	AUTH_UNAUTHORIZED, AUTH_CONFLICT_MAIL, AUTH_CONFLICT_USERNAME, AUTH_FORBIDDEN, VALIDATION_ERROR, INTERNAL_ERROR,
	NOT_FOUND, BAD_REQUEST, INVALID_TOKEN

}
